### ISSUE TITLE
랜딩 화면 개발

### ISSUE THREAD

**Issue by jungwookim** [green-labs/liar-game#2]
- 배너 삽입
- 캐릭터 랜덤 생성
- 닉네임 입력
- 입장 버튼 - 로비 입장해야함
  - setCookie("my_nickname")
  - 화면 전환
  - 전환 직후 ws 연결

![image](https://user-images.githubusercontent.com/50188177/185587047-97082445-6c7a-49f6-a98f-8e3a10078794.png)

**Comment by wickedev** [comment]
Play 가 아닌 입장 이여야 할 것 같습니다.

**Comment by wickedev** [comment]
https://www.dafont.com/daimonion.font
https://noonnu.cc/font_page/15
https://noonnu.cc/font_page/694

사용하면 어울릴 만한 폰트 몇개 들고 왔습니다

**Comment by wickedev** [comment]
웹소켓 예제입니다 https://github.com/tinymce/rescript-webapi/pull/34/files
